name: code_generation
version: 2.0.2
description: Generate a new EDNetCore project.

homepage: https://github.com/ednet-dev/cms/packages/ednet-core/code_generation
documentation: https://github.com/ednet-dev/cms/packages/ednet-core/code_generation

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  test: ^1.22.0
  yaml: ^3.1.1

  ednet_core:
    path: ../ednet_core

