name: ednet_core_gen
version: 2.0.2
description: Generate a new EDNetCore project.

homepage: https://github.com/ednet-dev/ednet_core_gen
documentation: http://goo.gl/Fd08zZ

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  test: ^1.22.0

  ednet_core:
    path: ../../../ednet_cms/packages/ednet_core

